apiVersion: v1

kind: Service

metadata:

    name: mongoservice

spec:

    selector:

        app: webapp-db

        tier: backend

    ports:

    - port: 27017
      targetPort: 27017
      protocol: TCP

    clusterIP: None
