apiVersion: v1

kind: Service

metadata:

    name: webappservice

spec:

    selector:

        app: webapp-db

        tier: frontend

    ports:

    - port: 80
      targetPort: 8888
      protocol: TCP

    type: NodePort
